#!/usr/bin/env bash
#
# nddev-zcode-app installer — recreates a complete, version-stamped ~/.zcode
# from source on macOS (desktop) or Ubuntu (desktop/server).
#
# Usage:
#   cli-tools/scripts/install.sh [--platform macos|ubuntu] [--apply|--plan] [--help]
#
# Default mode is --plan (dry-run): it prints every action without touching disk.
# Use --apply to execute: it backs up the current ~/.zcode, lays down the clean
# build, writes a version stamp, and selectively restores runtime state
# (credentials, sessions, db, certs) from the backup.
#
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="$SCRIPT_DIR/lib"

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"
# shellcheck source=lib/version.sh
. "$LIB_DIR/version.sh"

APPLY=0
PLATFORM="auto"

usage() {
  cat <<'EOF'
Usage: cli-tools/scripts/install.sh [--platform macos|ubuntu] [--apply|--plan] [--help]

Recreates a complete, version-stamped ~/.zcode from source.

Options:
  --platform macos|ubuntu   Target platform (default: auto-detect from uname).
  --apply                   Execute the install (default is --plan / dry-run).
  --plan | --dry-run        Print actions without writing (default).
  -h, --help                Show this help.

Backup convention:
  The current ~/.zcode is moved to ~/.zcode-backups/<N>-<DD.MM.YYYY>-<VERSION>-old.zcode
  where N is a 1-9 rotation slot and VERSION is the build being backed up.

Restore policy (from backup):
  Always restored: v2/credentials.json, v2/certs/, cli/agents/, cli/db/, cli/artifacts/
  Never restored:  cli/log/, v2/logs/, v2/crash/, plugin cache (regenerated by ZCode)
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --platform)
      PLATFORM="${2:?--platform requires one of macos|ubuntu}"
      shift 2
      ;;
    --apply)
      APPLY=1
      shift
      ;;
    --plan | --dry-run)
      APPLY=0
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

export NDDEV_DRY_RUN=$((1 - APPLY))

# Resolve platform.
if [ "$PLATFORM" = "auto" ]; then
  PLATFORM="$(nddev::detect_platform)" || exit 1
fi
if [ "$PLATFORM" != "macos" ] && [ "$PLATFORM" != "ubuntu" ]; then
  nddev::log "error" "Unsupported platform: $PLATFORM (expected macos|ubuntu)"
  exit 2
fi

ROOT="$(nddev::repo_root)"
RUNNER="$SCRIPT_DIR/$PLATFORM/install.sh"

if [ ! -x "$RUNNER" ]; then
  nddev::log "error" "Missing runner script: $RUNNER"
  exit 2
fi

nddev::section "nddev-zcode-app installer"
nddev::log "info" "mode: $([ "$APPLY" -eq 1 ] && echo 'APPLY' || echo 'PLAN (dry-run)')"
nddev::log "info" "platform: $PLATFORM"
nddev::log "info" "repo root: $ROOT"

# Validate prerequisites before delegating to the runner.
nddev::require_cmd git required || exit 1
nddev::require_cmd python3 required || exit 1

# Hand off to the platform runner. common.sh and version.sh stay sourced.
exec "$RUNNER"
