#!/usr/bin/env bash
#
# Selective restore of runtime state from a backup into a freshly built ~/.zcode.
#
# Invoked by the build library (NDDEV_BACKUP=<backup dir> NDDEV_TARGET=<zcode home>).
# Restores user-auth and session/runtime state so you stay logged in and keep history.
# Never restores logs, crash dumps, or plugin cache (ZCode regenerates those).
#
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
. "$SCRIPT_DIR/lib/common.sh"

BACKUP="${NDDEV_BACKUP:-}"
TARGET="${NDDEV_TARGET:-}"

if [ -z "$BACKUP" ] || [ -z "$TARGET" ]; then
  nddev::log "error" "NDDEV_BACKUP and NDDEV_TARGET must be set"
  exit 2
fi
if [ ! -d "$BACKUP" ]; then
  nddev::log "error" "backup directory not found: $BACKUP"
  exit 2
fi

# Files/dirs that are ALWAYS restored (auth + session + runtime data).
# Format: "backup-relative path : target-relative path".
RESTORE_PATHS=(
  "v2/credentials.json:v2/credentials.json"
  "v2/certs:v2/certs"
  "cli/agents:cli/agents"
  "cli/db:cli/db"
  "cli/artifacts:cli/artifacts"
)

# Paths that are NEVER restored (pure runtime junk / regenerated by ZCode).
NEVER_RESTORE=(
  "cli/log"
  "v2/logs"
  "v2/crash"
  "cli/plugins/cache"
)

nddev::log "info" "backup: $BACKUP"
nddev::log "info" "target: $TARGET"

restored=0
skipped=0

for entry in "${RESTORE_PATHS[@]}"; do
  src="${BACKUP}/${entry%%:*}"
  dest="${TARGET}/${entry##*:}"

  if [ ! -e "$src" ]; then
    nddev::log "info" "not in backup (skip): ${entry%%:*}"
    skipped=$((skipped + 1))
    continue
  fi

  if [ "${NDDEV_DRY_RUN:-1}" -eq 1 ]; then
    printf '[DRY-RUN] restore %q -> %q\n' "$src" "$dest"
    restored=$((restored + 1))
    continue
  fi

  # Ensure parent dir exists, then copy over the fresh build.
  mkdir -p "$(dirname "$dest")"
  cp -R "$src" "$dest"
  nddev::log "ok" "restored: ${entry##*:}"
  restored=$((restored + 1))
done

nddev::log "info" "restored $restored path(s), $skipped absent in backup"

if [ "${NDDEV_DRY_RUN:-1}" -eq 1 ]; then
  printf '[DRY-RUN] never-restored (regenerated by ZCode): %s\n' "${NEVER_RESTORE[*]}"
fi
