name: dependency-review

on:
  pull_request:
    branches: [main]

permissions: {}

concurrency:
  group: dependency-review-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  dependency-review:
    name: Dependency review
    permissions:
      contents: read
      pull-requests: write # Comment when dependency policy rejects a change.
    uses: NDDev-it-com/ci-workflows/.github/workflows/public-dependency-review.yml@f6ea891f09653b8d449098817c8acfdb510731f6 # 0.14.0-dev
