name: scorecard

on:
  push:
    branches: [main]
  schedule:
    - cron: "40 7 * * 1"

permissions:
  contents: read

concurrency:
  group: scorecard-${{github.ref}}
  cancel-in-progress: false

jobs:
  scorecard:
    name: OpenSSF Scorecard
    uses: NDDev-it-com/nddev-ci-workflows/.github/workflows/public-scorecard-json.yml@f4b2971fd38896d033a3bcfe0ee079368c7fd6fc # 0.3.0
