name: secret-scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  secret-scan:
    name: Secret scan
    uses: NDDev-it-com/nddev-ci-workflows/.github/workflows/secret-scan.yml@f4b2971fd38896d033a3bcfe0ee079368c7fd6fc # 0.3.0
