name: secret-scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: secret-scan-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  secret-scan:
    name: Secret scan
    uses: NDDev-it-com/ci-workflows/.github/workflows/secret-scan.yml@f6ea891f09653b8d449098817c8acfdb510731f6 # 0.14.0-dev
