name: zizmor

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "50 7 * * 1"
  workflow_dispatch:

permissions: {}

concurrency:
  group: zizmor-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  zizmor:
    name: zizmor (SARIF)
    permissions:
      contents: read
      security-events: write # Publish workflow-analysis results to code scanning.
    uses: NDDev-it-com/ci-workflows/.github/workflows/zizmor-sarif.yml@f6ea891f09653b8d449098817c8acfdb510731f6 # 0.14.0-dev
    with:
      persona: pedantic
      min_severity: low
